#!/bin/bash
#doc: copy   Copies a disk.

SRC="$1"
DEST="$2"

git rev-parse "$SRC" >/dev/null 2>&1 || {
  echo "branch '$SRC' does not exist"
  exit 1
}

git rev-parse "$DEST" >/dev/null 2>&1 && {
  echo "branch '$DEST' already exists"
  exit 1
}

git branch "$DEST" "$SRC" 2>/dev/null \
   || echo "'$DEST' is not a valid branch name"

