#!/bin/bash

#doc: play   Play mp3 or m4a files in the current directory

START="${1:-1}"

imgcat album-small.* 2>/dev/null
cat metadata.txt 2>/dev/null
echo

ls *.{mp3,m4a} 2>/dev/null | tail +"$START" | (
  while read filename; do
    echo "$filename"
    afplay "$filename"
  done
)
